version: "3.7"
services:
  ehr-api:
    image: ehr-api
    restart: always
    build: .
    ports:
      - 8080-8999:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: "mysql"
    volumes:
      - /home/Desktop/newDB
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ehr
      MYSQL_ROOT_PASSWORD: root123